# 
#
# Generated by dumpDCWorkflow.py written by Sebastien Bigaret
# Original workflow id/title: ejsubscriber_workflow/eJSubscriber Workflow
# Date: 2006/11/10 09:41:00.676 GMT+1
#
# WARNING: this dumps does NOT contain any scripts you might have added to
# the workflow, IT IS YOUR RESPONSABILITY TO MAKE BACKUPS FOR THESE SCRIPTS.
#
# No script detected in this workflow
# 
"""
Programmatically creates a workflow type
"""
__version__ = "$Revision: 1.1.1.1 $"[11:-2]

from Products.CMFCore.WorkflowTool import addWorkflowFactory

from Products.DCWorkflow.DCWorkflow import DCWorkflowDefinition

def setupEjsubscriber_workflow(wf):
    "..."
    wf.setProperties(title='eJSubscriber Workflow')

    for s in ['active', 'waiting', 'deactive']:
        wf.states.addState(s)
    for t in ['deactivate', 'activate', 'reactivate']:
        wf.transitions.addTransition(t)
    for v in ['action', 'time', 'comments', 'actor', 'review_history']:
        wf.variables.addVariable(v)
    for l in ['reviewer_queue']:
        wf.worklists.addWorklist(l)
    for p in ('Access contents information', 'Modify portal content', 'View'):
        wf.addManagedPermission(p)
        

    ## Initial State
    wf.states.setInitialState('waiting')

    ## States initialization
    sdef = wf.states['active']
    sdef.setProperties(title="""Active (Subscriber will get e-mails)""",
                       transitions=('deactivate',))
    sdef.setPermission('Access contents information', 1, ['Anonymous'])
    sdef.setPermission('Modify portal content', 1, ['Anonymous'])
    sdef.setPermission('View', 1, ['Anonymous'])

    sdef = wf.states['waiting']
    sdef.setProperties(title="""Wating For Activation""",
                       transitions=('activate',))
    sdef.setPermission('Access contents information', 1, ['Anonymous'])
    sdef.setPermission('Modify portal content', 1, ['Anonymous'])
    sdef.setPermission('View', 1, ['Anonymous'])

    sdef = wf.states['deactive']
    sdef.setProperties(title="""Deactive (Subscriber will not get e-mails)""",
                       transitions=('activate', 'reactivate'))
    sdef.setPermission('Access contents information', 1, [])
    sdef.setPermission('Modify portal content', 1, [])
    sdef.setPermission('View', 1, [])


    ## Transitions initialization
    tdef = wf.transitions['deactivate']
    tdef.setProperties(title="""Deactivate""",
                       new_state_id="""deactive""",
                       trigger_type=1,
                       script_name="""""",
                       after_script_name="""""",
                       actbox_name="""Deactivate""",
                       actbox_url="""""",
                       actbox_category="""workflow""",
                       props={'guard_permissions': 'Manage portal'},
                       )

    tdef = wf.transitions['activate']
    tdef.setProperties(title="""Activate""",
                       new_state_id="""active""",
                       trigger_type=1,
                       script_name="""""",
                       after_script_name="""""",
                       actbox_name="""Activate""",
                       actbox_url="""""",
                       actbox_category="""workflow""",
                       props={'guard_permissions': 'View'},
                       )

    tdef = wf.transitions['reactivate']
    tdef.setProperties(title="""Reactivate""",
                       new_state_id="""active""",
                       trigger_type=1,
                       script_name="""""",
                       after_script_name="""""",
                       actbox_name="""Reactivate""",
                       actbox_url="""""",
                       actbox_category="""workflow""",
                       props={'guard_permissions': 'Manage portal'},
                       )

    ## State Variable
    wf.variables.setStateVar('review_state')

    ## Variables initialization
    vdef = wf.variables['action']
    vdef.setProperties(description="""The last transition""",
                       default_value="""""",
                       default_expr="""transition/getId|nothing""",
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['time']
    vdef.setProperties(description="""Time of the last transition""",
                       default_value="""""",
                       default_expr="""state_change/getDateTime""",
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['comments']
    vdef.setProperties(description="""Comments about the last transition""",
                       default_value="""""",
                       default_expr="""python:state_change.kwargs.get('comment', '')""",
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['actor']
    vdef.setProperties(description="""The ID of the user who performed the last transition""",
                       default_value="""""",
                       default_expr="""user/getId""",
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['review_history']
    vdef.setProperties(description="""Provides access to workflow history""",
                       default_value="""""",
                       default_expr="""state_change/getHistory""",
                       for_catalog=0,
                       for_status=0,
                       update_always=0,
                       props={'guard_permissions': 'Request review; Review portal content'})

    ## Worklists Initialization
    ldef = wf.worklists['reviewer_queue']
    ldef.setProperties(description="""Reviewer tasks""",
                       actbox_name="""Pending (%(count)d)""",
                       actbox_url="""%(portal_url)s/search?review_state=pending""",
                       actbox_category="""global""",
                       props={'guard_permissions': 'Review portal content', 'var_match_review_state': 'pending'})


def createEjsubscriber_workflow(id):
    "..."
    ob = DCWorkflowDefinition(id)
    setupEjsubscriber_workflow(ob)
    return ob

addWorkflowFactory(createEjsubscriber_workflow,
                   id='ejsubscriber_workflow',
                   title='eJSubscriber Workflow')

    